# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a396096a3782e690ec3126082781bd87a7873b1aab5a801709469b55e4c8e94069a45e7e8ab6cf7b961a4549f8672686caa44f670897ad9678f3c37882c5e7ed

test:
  secret_key_base: 1fbae896115510a96a2e5aebf4447d4a735ac5cbeb9f2713dbcb4914f2120a1fb6f3d2a25809ced8590888aeb3cba9988a9a76d6502049e74fbeb5c0949704b2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
